name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Rebuild generated files
        run: npm run prepare-pr
      - name: Validated generated API and doc changes have been committed
        run: ./validate-generated-files.sh
      - name: Publish
        run: npm publish --provenance
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
